language: python
env:
  - DJANGO_SETTINGS_MODULE='momconnectkzn.testsettings' DATABASE_URL='postgres://postgres:@/test_momconnectkzn'
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
before_script:
  - psql -c 'create database test_momconnectkzn;' -U postgres
script:
  - flake8 momconnectkzn
  - ./manage.py test --with-coverage --cover-package=momconnectkzn
after_success:
  - coveralls
